### PR TITLE
[WIP] feat: async await

### PR DESCRIPTION
**Pull request by hacdias**
More background about this effort: https://github.com/ipfs/js-ipfs/issues/1670.

**Depends on:**
- https://github.com/ipld/interface-ipld-format/pull/47
- (Coming PR for `multihashing-async` module)

### CODE REVIEW

**Comment by hacdias** [comment]
@alanshaw @vmx what's the state of this?

**Comment by vmx** [comment]
@hacdias https://github.com/ipfs/js-ipfs/issues/1670#issuecomment-453962298

**Comment by hacdias** [comment]
@vmx gotcha! Then, perhaps, shouldn't we close this PRs on ipld side? Since there are major refactorings coming?

**Comment by vmx** [comment]
I first thought "yes, let's close it". But then after a second thought I might leave it open. I personally look at open issues/PRs more than on closed one. There's certainly a discoverability issue here, that the refactoring is coming. So my hope would be that anyone trying to hop in to help with the async/await endeavour, to find those already open PRs and won't work on it.

What do you think @hacdias?

**Comment by hacdias** [comment]
@vmx I agree with the (in)visibility of the issues/PRs when they're closed/open. Although I also find it distracting and we always have https://github.com/ipfs/js-ipfs/issues/1670 to keep track of all of the async await changes.

**Comment by vmx** [comment]
Superseded by https://github.com/ipld/js-ipld-raw/pull/32.

**Pull request closed without merging**
